### PR TITLE
chore: Rename clusters folder to cluster for L1 cluster resource and syncs with CFN

### PR DESCRIPTION
**Pull request by lantoli**
Rename clusters folder to cluster for L1 cluster resource and syncs with CFN

_Jira ticket:_ CLOUDP-248306

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code
- [x] I have tested the CDK constructor in a CFN stack. See [TESTING.md](../TESTING.md)
- [x] If changes include removal or addition of 3rd party GitHub actions, I updated our internal document. Reach out to the APIx Integration slack channel to get access to the internal document.

### CODE REVIEW

**Review by oarbusi — APPROVED** [review]

**Comment by lantoli** [comment]
waiting for team decision before merging

**Comment by lockenj** [comment]
This fix breaks backwards compatibility. Yesterday on version `v3.5.1` the below snippet worked.

```
this.#_atlasCluster.connectionStrings.standardSrv
``` 

Now in `v3.5.2` I get error: 
```
TypeError: Cannot read properties of undefined (reading 'standardSrv')
```

**Comment by lockenj** [comment]
It appears that the visibility of this property was changed.

From:
```
public readonly connectionStrings: ConnectionStrings;
```

To:
```
readonly connectionStrings?: ConnectionStrings;
```

**Comment by lantoli** [comment]
sorry @lockenj for the inconvenience.

that property shouldn't have existed in the first place. It was manually added so it was not synced with underlaying CFN resource. This CDK L1 resource must be generated automatically.

If you need to access those properties, you can do things like: 
```
this.#_atlasCluster.getAtt("ConnectionStrings.StandardSrv")
```
you can take this PR code change as a reference.

thanks

**Comment by romulus-ai** [comment]
Thanks für the fast response, @lantoli your fix works very well! However, would be nice to access the connection strings of a generated cluster in an easier way (i.e. like before). Additionally may if you guys break backwards compatibility try not to make a patch release :)

**Comment by lantoli** [comment]
I agree about accessing in an easier way but this is more a CDK limitation in L1 constructs.

I understand your point about breaking compatibility and will review it for future changes, in this case we thought of this as a fix as that attribute shouldn't have existed in the first place. 

Thanks for your understanding, any other question please let us know

**Pull request merged**
