### PR TITLE
INTMDB-905: Refreshed CDK for cluster 

### PR DESCRIPTION
**Pull request by Adelmar92**
## Proposed changes

Cluster CDK was updated for:

- https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/600
- https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/611

_Jira ticket:
- [INTMDB-862](https://jira.mongodb.org/browse/INTMDB-862)
- [INTMDB-905)](https://jira.mongodb.org/browse/INTMDB-905)

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s): 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code
- [ ] I have tested the CDK constructor in a CFN stack. See [TESTING.md](../TESTING.md)

### CODE REVIEW

**Review by andreaangiolillo — COMMENTED** [review]
Did we release the cluster CFN resource already? Let's merge this once the changes are available in cfn

**Comment by Adelmar92** [comment]
> Did we release the cluster CFN resource already? Let's merge this once the changes are available in cfn

Yes @andreaangiolillo is been already released

**Review by andreaangiolillo — COMMENTED** [review]
Could you also update the submodule with the cfn repo with the latest changes?

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Pull request merged**
