### PR TITLE
doc: Add limitations section to top level readme

### PR DESCRIPTION
**Pull request by zach-carr**
Note: reviews for this PR here: https://github.com/mongodb/mongodbatlas-cloudformation-resources/pull/682

Documentation update - [DOCSP-29472](https://jira.mongodb.org/browse/DOCSP-29472)
- Adds a limitations section

A markdown viewer I found online, if it's helpful for copy review: https://markdownlivepreview.com/

### CODE REVIEW

**Review by sarahsimpers — APPROVED** [review]
Approved with one suggestion to make the meaning of 2 more clear (see other PR)

**Comment by zach-carr** [comment]
Hey @andreaangiolillo, could you review this whenever you have time? Thanks in advance

**Comment by andreaangiolillo** [comment]
@zach-carr The PR does not show any changes. I also already reviewed the PR in the description. What am I missing? 🤔

**Comment by zach-carr** [comment]
Sorry about that @andreaangiolillo, my mistake - I was trying to pass an evergreen check and went in circles. I added the changes back (you did already approve them, but I can't merge myself without a review from someone with write access)

**Comment by andreaangiolillo** [comment]
I see this [error](https://github.com/mongodb/awscdk-resources-mongodbatlas/actions/runs/6112032313/job/16588641793?pr=116#step:8:9)

> Error: Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch.


Make sure to run the command `npx projen` inside your fork and commit any changes in your folder.

**Comment by zach-carr** [comment]
Hey @andreaangiolillo, I've been messing with this for a while but can't clear this error. `npx projen` returns `default | node .projenrc.js` whatever branch I'm on. 

I created a new branch against upstream/main to start from scratch ([new PR](https://github.com/mongodb/awscdk-resources-mongodbatlas/pull/130)), but I'm still getting this. There don't appear to be any differences aside from the README update. I must not understand this check properly, could you point me in the right direction? 

The error is still:
`Error: Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch.
diff --git a/API.md b/API.md`

I've updated my branch, I've tried creating a new branch off of main, and there are not any changes in the API.md file. I'll keep working on this, but thanks in advance for any advice

**Review by marcosuma — DISMISSED** [review]

**Pull request closed without merging**
